### ISSUE TITLE
Running the SuperH boot program causes crash

### ISSUE THREAD

**Issue by RossComputerGuy** [lxdream/lxdream#25]
Running sh-boot on from the binary load option causes it to crash after resetting the emulator:
```
lxdream: sh4/sh4trans.c:237: xlat_get_code_by_vma: Assertion `IS_IN_ICACHE(sh4r.pc)' failed.
```

**Comment by nkeynes** [comment]
That assertion is typically triggered by a branch to an unmapped region of memory; that should be changed to just halt and report an error rather than asserting out - will fix this.

That said, to get to this point either the program we're running is buggy or something else has gone badly wrong already; If this is an open source/public domain program, could you please provide a link where it can be found for testing?

**Comment by RossComputerGuy** [comment]
I've got a repo with some fixes to sh-boot, https://github.com/ronixos/sh-boot. The last time it had gotten any fixes or anything was 2001.

**Comment by nkeynes** [comment]
I managed to get sh-stub.elf to build (using binutils 2.21.1 and gcc 4.6.4), running it up
```
$ lxdream -e sh-stub.elf
21:55:22 ACFF103A WARN  SCSPTR2 not implemented: Write 00000080

SH IPL+g version 0.9, Copyright (C) 2000 Free Software Foundation, Inc.

This software comes with ABSOLUTELY NO WARRANTY; for details type `w'.
This is free software, and you are welcome to redistribute it under
certain conditions; type `l' for details.
```

**Comment by RossComputerGuy** [comment]
sh-stub.elf is not supposed to run, you build the stub then build the tools/dreamcast/ suff.

**Comment by nkeynes** [comment]
Fixed the assertion - now halts cleanly when branching to an invalid address.
Looking at the code, I'm not sure how the kernel-boot binary would actually work; I'll have to test on the actual DC.

**Comment by nkeynes** [comment]
Confirmed image fails to run on real hardware. Closing issue
